Only test version of vim that work with ci
Building with v8.0 fails with a warning explaining that this version of
vim doesn't configure itself correctly:

> Warning: This version of Vim has a bug where ./configure cannot find a
> terminal library correctly. See the following issue for more details:
> https://github.com/rhysd/action-setup-vim/issues/38
>
> Error: Command './configure --prefix=/Users/runner/vim-v8.0.0000 --with-features=huge --enable-fail-if-missing' exited non-zero status 1:
> configure: error: NOT FOUND!
> You need to install a terminal library; for example ncurses.
> Or specify the name of the library with --with-tlib.

Use the version of vim that action-setup-vim identified as working. Also
add v9 so we're still testing the same number of versions.